spring:
  application:
    name: android_sdp_server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: your_password
    url: jdbc:mysql://<host>:<port>/<dbName>
springdoc:
  swagger-ui:
    path: ""
    enabled: true
  api-docs:
    path: /api-docs
